name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify (${{ matrix.os }}, ${{ matrix.name }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - name: Pinned
            cargo_flags: '--locked'
            use_stable: false
          - name: Stable
            cargo_flags: '--locked'
            use_stable: true
          - name: Unlocked
            cargo_flags: ''
            use_stable: true

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: python -m pip install -r scripts/requirements.txt

      - name: Check generated code
        run: |
          python scripts/make_rust_vectors.py
          git diff --exit-code

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.use_stable && 'stable' || '' }}
          override: ${{ matrix.use_stable }}
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.name }}-${{ hashFiles('**/rust-toolchain.toml', '**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-

      - name: Remove lockfile if testing unlocked
        if: matrix.name == 'Unlocked'
        run: rm -f Cargo.lock

      - name: Check formatting
        if: matrix.name == 'Pinned' && runner.os == 'Linux'
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-targets ${{ matrix.cargo_flags }} -- -D warnings

      - name: Build
        run: cargo build --all-targets ${{ matrix.cargo_flags }}

      - name: Run tests
        run: cargo test --all-targets ${{ matrix.cargo_flags }}

      - name: Run doc tests
        run: cargo test --doc ${{ matrix.cargo_flags }}

      - name: Build examples
        run: cargo build --examples ${{ matrix.cargo_flags }}

      - name: Run cargo vet
        if: matrix.name == 'Pinned' && runner.os == 'Linux'
        run: |
          cargo install cargo-vet --locked
          cargo vet

      - name: Check no_std
        if: runner.os == 'Linux'
        run: |
          rustup target add thumbv7m-none-eabi
          cargo check --target thumbv7m-none-eabi ${{ matrix.cargo_flags }}
